# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Auto Bump version

on:
  pull_request:
    types:
      - closed
    branches:
      - master
      - beta
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
          fetch-depth: 0
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          VERBOSE: true
          PRERELEASE: ${{ github.base_ref == 'beta' }}
          RELEASE_BRANCHES: master,beta
          DEFAULT_BUMP: patch
  release:
    runs-on: windows-latest
    needs: bump
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: Set up node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Set up wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Check wails install
        run: wails doctor
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            "./frontend/node_modules"
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Build Windows Release
        run: wails build -platform windows/amd64 -nsis
      - name: Release Windows
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: ${{ github.base_ref == 'beta' }}
          draft: true
          files: |
            ./build/bin/*.exe
 