# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Tagged Release

on:
  push:
    tags:
    - "v*"
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: Set up node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Set up wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Check wails install
        run: wails doctor
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            "./frontend/node_modules"
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Build Windows Release
        run: wails build -platform windows/amd64 -nsis
      - name: Release Windows
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: github.event_name == 'push' && contains(github.ref, 'beta')
          draft: true
          files: |
            ./build/bin/*.exe
      
