# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Tagged Release

on:
  workflow_run:
    workflows: ["Auto Bump version"]
    types:
      - completed
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Check version format
        uses: nowsprinting/check-version-format-action@v3
        id: version
        with:
          prefix: 'v'
      - name: Check version is valid
        run: |
          echo "This is a valid version"
          exit 1
        if: steps.version.outputs.is_valid == 'false'
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: Set up node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Set up wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Check wails install
        run: wails doctor
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            "./frontend/node_modules"
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Build Windows Release
        run: wails build -platform windows/amd64 -nsis
      - name: Release Windows
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: steps.version.outputs.is_stable == 'false'
          draft: true
          files: |
            ./build/bin/*.exe
      
